-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 20, 2024 at 12:08 PM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rcc_chatbot`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `category_id` int NOT NULL AUTO_INCREMENT,
  `category_name` varchar(255) NOT NULL,
  PRIMARY KEY (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`category_id`, `category_name`) VALUES
(1, 'greetings and goodbyes'),
(2, 'linux_basic_commands');

-- --------------------------------------------------------

--
-- Table structure for table `dataset`
--

DROP TABLE IF EXISTS `dataset`;
CREATE TABLE IF NOT EXISTS `dataset` (
  `id` int NOT NULL AUTO_INCREMENT,
  `category_id` int NOT NULL,
  `patterns` text NOT NULL,
  `responses` text NOT NULL,
  `y_tags` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `dataset`
--

INSERT INTO `dataset` (`id`, `category_id`, `patterns`, `responses`, `y_tags`) VALUES
(1, 1, 'Hi|Hey|How are you|Is anyone there?|Hello|Good day', 'Hey :-)|Hello,thanks for visiting|Hi there, what can I do for you?|Hi there, how can I help?', 'greeting'),
(2, 1, 'Bye|See you later|Goodbye', 'See you later, thanks for visiting|Have a nice day|Bye! Come back again soon.', 'goodbye'),
(3, 2, 'What is the command to list files or directories in Linux?|How do I list files or directories in Linux?|How can I see the files or directories in a directory?|Show me the files or directories in a folder|Show me the command to list files or directories|ls command|ls in linux|ls --help|How do I list hidden files in a directory in Linux?|How can I get more details about files in a directory in Linux?', 'The command to list files/directories in Linux is ls. Here are some options for the ls command:\n-a: Include directory entries whose names begin with a dot (.) to list hidden files\n-l: Use a long listing format for detailed information about files\n-h: With -l, print sizes in human-readable format (e.g., 1K 234M 2G)\n-R: List subdirectories recursively\n-t: Sort by modification time, newest first\n--help: Display help information', 'linux_ls'),
(4, 2, 'How do I change directories in Linux?|What command do I use to move to a different folder?|Change directory command in Linux|How do I change directories?|What is the command to change directory?|cd command|cd in linux|cd --help|How do I go back to the previous directory in Linux?|How can I quickly go to my home directory in Linux?', 'The cd command is used to change directories. Here are some common uses of the cd command:\n-cd [directory]: Change to the specified directory\n-cd ..: Move one level up to the parent directory\n-cd ~: Move to the home directory\n-cd -: Switch back to the previous directory\n--help: Display help information', 'linux_cd'),
(5, 2, 'What is the command to show the current directory in Linux?|How do I find out which directory I\'m in?|Print working directory command in Linux|How do I print the current directory?|What is the command to show current directory?|pwd command|pwd in linux|pwd --help|What does pwd stand for in Linux?', 'The pwd command prints the current working directory. Here are some options for the pwd command:\n-L: Display the logical current working directory\n-P: Display the physical current working directory (with symbolic links resolved)\npwd stands for \'print working directory\'.\n--help: Display help information', 'linux_pwd'),
(6, 2, 'How do I create a directory in Linux?|What command is used to make a new folder?|Create directory command in Linux|How do I create a directory?|What is the command to create a directory?|mkdir command|mkdir in linux|mkdir --help|I want information about mkdir command|How do I create multiple directories at once in Linux?', 'The mkdir command creates a new directory. Here are some options for the mkdir command:\n-m: Set file mode (permissions) when creating the directory\n-p: Make parent directories as needed\n-v: Print a message for each created directory\nTo create multiple directories at once, use the command with braces: mkdir -p dir1/dir2/dir3 to create dir1, dir2 within dir1, and dir3 within dir2.\n--help: Display help information', 'linux_mkdir'),
(7, 2, 'How can I view the contents of a file in Linux?|What is the command to read a file in Linux?|Show me the contents of a file in Linux|How do I display the contents of a file?|What is the command to create a directory?|cat command|cat in linux|cat --help|What is the command to view file contents?|How can I view a file with line numbers in Linux?', 'The cat command concatenates and displays the contents of a file. Here are some options for the cat command:\n-n: Number all output lines to view the file with line numbers\n-b: Number non-blank output lines\n-s: Suppress repeated empty output lines\nTo view a file with line numbers, use cat -n filename.\n--help: Display help information', 'linux_cat'),
(8, 2, 'How do I change file permissions in Linux?|What command is used to modify file permissions?|Change file permissions command in Linux?|How do I change file permissions?|What is the command to change file permissions?|chmod command|chmod in linux|chmod --help|What do the numbers mean in the chmod command?', 'The chmod command changes the file permissions. Here are some options for the chmod command:\n-R: Change files and directories recursively\n-v: Output a diagnostic for every file processed\n-c: Like -v, but report only when a change is made\n--help: Display help information\nThe numbers in the chmod command represent the permissions: 4 for read (r), 2 for write (w), and 1 for execute (x). For example, chmod 755 filename gives the owner full permissions (7), and the group and others read and execute permissions (5 each).', 'linux_chmod'),
(9, 2, 'How do I change the owner of a file in Linux?|What is the command to change file ownership in Linux?|Change file ownership command in Linux|How do I change file owner?|What is the command to change file owner?|chown command|chown in linux|chown --help|How do I change both the owner and group of a file in Linux?', 'The chown command changes the file owner and group. Here are some options for the chown command:\n-R: Operate on files and directories recursively\n-v: Verbosely explain what is being done\n--help: Display help information\nTo change both the owner and group of a file, use chown owner:group filename.', 'linux_chown'),
(10, 2, 'How can I see the running processes in Linux?|What  command is used to display processes?|List processes command in Linux|How do I display active processes?|What is the command to show active processes?|ps command|ps in linux|ps --help|How do I see all processes running by a specific user in Linux?', 'The ps command displays active processes. Here are some options for the ps command:\n-e: Select all processes\n-f: Full format listing\n-u [user]: Display processes of a specific user\nTo see all processes running by a specific user, use ps -u username.\n--help: Display help information', 'linux_ps'),
(11, 2, 'How do I monitor processes in real-time in Linux?|What  command gives a dynamic view of system processes in Linux?|Display top processes command in Linux|How do I display real-time process information?|What is the command for real-time process information?|top command|top in linux|top --help|How can I sort the processes by memory usage in the top command?', 'The top command provides a real-time view of the system\'s processes. Here are some options for the top command:\n-d: Delay between updates\n-p [pid]: Monitor specific PIDs\n-u [user]: Monitor processes for a specific user\nTo sort the processes by memory usage, press M while top is running.\n--help: Display help information', 'linux_top'),
(12, 2, 'How do I terminate a process in Linux?|What is the command to end a process in Linux?|Terminate process command in Linux|How do I kill a process?|What is the command to terminate a process?|kill command|kill in linux|kill --help|How to kill a process in linux?|How do I find the process ID (PID) to use with the kill command?', 'The kill command terminates a process. Here are some options for the kill command:\n-9: Forcefully terminate a process\n-l: List all signal names\nTo find the process ID (PID) to use with the kill command, you can use the ps or top command.\n--help: Display help information', 'linux_kill'),
(13, 2, 'What is the command to kill processes by name in Linux?|How can I end processes with a specific name in Linux?|Kill processes by name command in Linux?|How do I kill a process by name?|What is the command to terminate processes by name?|pkill command|pkill in linux|pkill --help', 'The pkill command sends a signal to processes based on their name. Here are some options for pkill command:\n-e: Display the process name in verbose mode\n-f: Match against full argument lists\n-s [signal]: Specify the signal to send\n--help: Display help information', 'linux_pkill'),
(14, 2, 'How do I check get the IP address configuration in Linux?|What command shows network configuration in Linux?|Display IP configuration command in Linux|How do I configure a network interface?|What is the command to configure network interfaces?|ifconfig command|ifconfig in linux|ifconfig --help', 'The ifconfig command is used to configure network interfaces. Here are some options for ifconfig command:\r\n-a: Display all interfaces\r\n-up: Activate an interface\r\n-down: Deactivate an interface\r\n-netmask [address]: Set the IP netmask\r\n-broadcast [address]: Set the broadcast address\r\n--help: Display help information\r\nNote: In many modern Linux distributions, the ip command is preferred for network configuration. For example, ip addr show can be used to display IP address information.', 'linux_ifconfig'),
(25, 2, 'What command is used to test network connectivity in Linux?|How do I check if my network connection is working in Linux?|Test network connectivity command in Linux?|How do I test network connectivity?|What is the command to send ICMP ECHO_REQUEST to network hosts?|ping command|ping in linux|ping --help|How do I stop a ping command that is running?', 'The ping command tests the network connectivity to a server. Here are some options for the ping command:\n-c [count]: Send a specific number of packets\n-i [interval]: Set the interval between packets\n-s [size]: Set the packet size\nTo stop a ping command that is running, press Ctrl+C.\n--help: Display help information', 'linux_ping'),
(26, 2, 'How can I check network statistics in Linux?|What command shows network connections in Linux?|Display network statistics command in Linux?|How do I display network connections?|What is the command to show network status?|netstat command|netstat in linux|netstat --help|How can I see the current network connections in Linux?', 'The netstat command displays network connections, routing tables, interface statistics, masquerade connections, and multicast memberships. Here are some options for the netstat command:\n-a: Show all connections (listening and non-listening)\n-t: Display TCP connections\n-u: Display UDP connections\n-p: Show the PID and name of the program to which each socket belongs\nTo see the current network connections, use netstat -an.\n--help: Display help information', 'linux_netstat'),
(27, 2, 'How can I move a file in Linux?|What command is used to move a file in Linux?|Display the command to move a file in Linux.|How do I move files to a new directory?|What is the command to rename a file?|mv command|mv in linux|mv --help|How can I move a directory in Linux?', 'The `mv` command in Linux is used to move files or directories from one location to another or to rename them. Here are some common usages of the `mv` command:\nTo move a file to a new directory:\n`mv filename.txt /path/to/directory/`\nTo rename a file:\n`mv oldname.txt newname.txt`\nTo move multiple files to a directory:\n`mv file1.txt file2.txt file3.txt /path/to/directory/`\nTo move a directory to a new location:\n`mv sourcedir /path/to/destination/`\nTo overwrite existing files without prompting:\n`mv -f sourcefile /path/to/destination/`\nTo use the interactive mode and prompt before overwriting:\n`mv -i sourcefile /path/to/destination/`\nFor more options, you can use `mv --help` to display help information.', 'linux_mv'),
(28, 2, 'How can I copy a file in Linux?|What command is used to copy a file in Linux?|Display the command to copy a file in Linux.|How do I copy files to a new directory?|What is the command to duplicate a file?|cp command|cp in linux|cp --help|How can I copy a directory in Linux?', 'The `cp` command in Linux is used to copy files and directories. Here are some common usages of the `cp` command:\nTo copy a file to a new location:\n`cp filename.txt /path/to/directory/`\nTo copy a file and rename it:\n`cp oldname.txt newname.txt`\nTo copy multiple files to a directory:\n`cp file1.txt file2.txt file3.txt /path/to/directory/`\nTo copy a directory and its contents recursively:\n`cp -r sourcedir /path/to/destination/`\nTo prompt before overwriting files:\n`cp -i sourcefile /path/to/destination/`\nTo preserve file attributes (e.g., timestamps, permissions):\n`cp -p sourcefile /path/to/destination/`\nFor more options, you can use `cp --help` to display help information.', 'linux_cp'),
(29, 2, 'How can I delete a file in Linux?|What command is used to remove a file in Linux?|Display the command to delete a file in Linux.|How do I remove files from a directory?|What is the command to delete a directory?|rm command|rm in linux|rm --help|How can I delete a directory in Linux?', 'The `rm` command in Linux is used to remove files and directories. Here are some common usages of the `rm` command:\nTo delete a file:\n`rm filename.txt`\nTo delete multiple files:\n`rm file1.txt file2.txt file3.txt`\nTo delete a directory and its contents recursively:\n`rm -r directoryname`\nTo forcefully delete a file without prompting:\n`rm -f filename.txt`\nTo prompt before every removal:\n`rm -i filename.txt`\nTo delete all files in a directory:\n`rm /path/to/directory/*`\nFor more options, you can use `rm --help` to display help information.', 'linux_rm'),
(30, 2, 'How can I create an empty file in Linux?|What command is used to create a new file in Linux?|Display the command to create an empty file in Linux.|How do I update the timestamp of a file?|What is the command to change file timestamps?|touch command|touch in linux|touch --help|How can I create multiple empty files in Linux?', 'The `touch` command in Linux is used to create empty files or update the timestamp of existing files. Here are some common usages of the `touch` command:\nTo create an empty file:\n`touch filename.txt`\nTo create multiple empty files:\n`touch file1.txt file2.txt file3.txt`\nTo update the timestamp of an existing file to the current time:\n`touch existingfile.txt`\nTo set a specific timestamp (e.g., Jan 1, 2024 12:34):\n`touch -t 202401011234 filename.txt`\nTo use a reference file\'s timestamp:\n`touch -r referencefile.txt targetfile.txt`\nFor more options, you can use `touch --help` to display help information.', 'linux_touch'),
(31, 2, 'How can I create a symbolic link in Linux?|What command is used to create a hard link in Linux?|Display the command to create a symbolic link in Linux.|How do I create hard links and symbolic links?|What is the command to link files?|ln command|ln in linux|ln --help|How can I link directories in Linux?', 'The `ln` command in Linux is used to create hard and symbolic links to files and directories. Here are some common usages of the `ln` command:\nTo create a hard link:\n`ln sourcefile.txt linkname.txt`\nTo create a symbolic link (symlink):\n`ln -s sourcefile.txt linkname.txt`\nTo create a symbolic link to a directory:\n`ln -s /path/to/source_directory /path/to/link_directory`\nTo create multiple hard links:\n`ln sourcefile1.txt sourcefile2.txt /path/to/destination_directory`\nTo force the creation of a symbolic link, even if the target exists:\n`ln -sf sourcefile.txt linkname.txt`\nFor more options, you can use `ln --help` to display help information.', 'linux_ln'),
(32, 2, 'How can I clear the terminal screen in Linux?|What command is used to clear the terminal in Linux?|Display the command to clear the terminal in Linux.|How do I clear the screen in Linux?|What is the command to reset the terminal display?|clear command|clear in linux|clear --help|How can I refresh the terminal in Linux?', 'The `clear` command in Linux is used to clear the terminal screen. Here are some common usages of the `clear` command:\nTo clear the terminal screen:\n`clear`\nTo clear the terminal screen and the scrollback buffer (using `reset`):\n`reset`\nFor more options, you can use `clear --help` to display help information.', 'linux_clear'),
(33, 2, 'How can I print text to the terminal in Linux?|What command is used to display a message in Linux?|Display the command to print a message in Linux.|How do I use the echo command in Linux?|What is the command to print text to the terminal?|echo command|echo in linux|echo --help|How can I use echo to display variables in Linux?', 'The `echo` command in Linux is used to display a line of text or a variable value to the terminal. Here are some common usages of the `echo` command:\nTo print a simple message:\n`echo \'Hello, World!\'`\nTo print the value of a variable:\n`echo $VARIABLE_NAME`\nTo print text without a trailing newline:\n`echo -n \'Hello, World!\'`\nTo enable interpretation of backslash escapes:\n`echo -e \'Hello\\nWorld\'`\nTo redirect the output to a file:\n`echo \'Hello, World!\' > output.txt`\nFor more options, you can use `echo --help` to display help information.', 'linux_echo'),
(34, 2, 'How can I view the contents of a file in Linux?|What command is used to display file contents page by page in Linux?|Display the command to view a file in Linux.|How do I use the less command in Linux?|What is the command to read file contents interactively?|less command|less in linux|less --help|How can I scroll through a file in Linux?', 'The `less` command in Linux is used to view the contents of a file one page at a time. Here are some common usages of the `less` command:\nTo view a file:\n`less filename.txt`\nTo scroll forward one page:\nPress the `Space` key.\nTo scroll backward one page:\nPress the `b` key.\nTo search for a pattern within the file:\nPress `/` followed by the search pattern and `Enter`.\nTo exit `less`:\nPress `q`.\nTo display line numbers:\n`less -N filename.txt`\nFor more options, you can use `less --help` to display help information.', 'linux_less'),
(35, 2, 'How can I get help for commands in Linux?|What command is used to display manual pages in Linux?|Display the command to access command documentation in Linux.|How do I use the man command in Linux?|What is the command to read manual pages in Linux?|man command|man in linux|man --help|How can I find information about specific commands?', 'The `man` command in Linux is used to display the manual pages for commands and other topics. Here are some common usages of the `man` command:\nTo view the manual page for a command:\n`man command_name`\nTo search for a specific keyword in manual pages:\n`man -k keyword`\nTo exit `man`:\nPress `q`.\nTo navigate within `man` pages:\nUse the arrow keys, `Page Up`, `Page Down`, or press `/` to search.\nFor more options, you can use `man --help` to display help information.', 'linux_man'),
(36, 2, 'How can I display system information in Linux?|What command is used to show system information in Linux?|Display the command to view system details in Linux.|How do I use the uname command in Linux?|What is the command to print system information?|uname command|uname in linux|uname --help|How can I find out the system kernel version?', 'The `uname` command in Linux is used to display system information. Here are some common usages of the `uname` command:\nTo display the kernel name:\n`uname -s`\nTo display the network node hostname:\n`uname -n`\nTo display the kernel release:\n`uname -r`\nTo display the machine hardware name:\n`uname -m`\nTo display the processor type:\n`uname -p`\nFor more options, you can use `uname --help` to display help information.', 'linux_uname'),
(37, 2, 'How can I find out the current user in Linux?|What command is used to display the current user in Linux?|Display the command to show the current user in Linux.|How do I use the whoami command in Linux?|What is the command to print the current username?|whoami command|whoami in linux|whoami --help|How can I determine my current login?', 'The `whoami` command in Linux is used to display the current user. Here\'s how you can use it:\nTo print the current username:\n`whoami`\nThis command is helpful when you need to know which user you are currently logged in as.\nFor more options, you can use `whoami --help` to display help information.', 'linux_whoami'),
(38, 2, 'How can I create or extract archives in Linux?|What command is used to manipulate archives in Linux?|Display the command to create or extract tar files in Linux.|How do I use the tar command in Linux?|What is the command to compress or decompress files and directories?|tar command|tar in linux|tar --help|How can I create a tarball?', 'The `tar` command in Linux is used to create, view, extract, and manipulate tar archives. Here are some common usages of the `tar` command:\nTo create a tar archive from files and directories:\n`tar -cvf archive.tar file1.txt file2.txt directory1`\nTo extract files from a tar archive:\n`tar -xvf archive.tar`\nTo compress files and directories into a gzip-compressed tarball:\n`tar -czvf archive.tar.gz file1.txt directory1`\nTo decompress a gzip-compressed tarball:\n`tar -xzvf archive.tar.gz`\nFor more options, you can use `tar --help` to display help information.', 'linux_tar'),
(39, 2, 'How can I search for text patterns in files in Linux?|What command is used to find specific text in files in Linux?|Display the command to search for patterns in files in Linux.|How do I use the grep command in Linux?|What is the command to filter lines matching a pattern?|grep command|grep in linux|grep --help|How can I search recursively in directories?', 'The `grep` command in Linux is used to search for text patterns in files. Here are some common usages of the `grep` command:\nTo search for a pattern in a single file:\n`grep \'pattern\' filename.txt`\nTo search for a pattern recursively in directories:\n`grep -r \'pattern\' /path/to/directory`\nTo search for a pattern and display line numbers:\n`grep -n \'pattern\' filename.txt`\nTo search for a pattern and ignore case:\n`grep -i \'pattern\' filename.txt`\nFor more options, you can use `grep --help` to display help information.', 'linux_grep'),
(40, 2, 'How can I display the beginning of a file in Linux?|What command is used to show the first lines of a file in Linux?|Display the command to view the top lines of a file in Linux.|How do I use the head command in Linux?|What is the command to print the first few lines of a file?|head command|head in linux|head --help|How can I show the first N lines of a file?', 'The `head` command in Linux is used to display the beginning of a file. Here are some common usages of the `head` command:\nTo display the first 10 lines of a file:\n`head filename.txt`\nTo display the first N lines of a file (e.g., 5 lines):\n`head -n 5 filename.txt`\nTo display the first part of multiple files:\n`head file1.txt file2.txt`\nTo display the first part of a file and follow it with contents of another file:\n`head file1.txt; cat file2.txt`\nFor more options, you can use `head --help` to display help information.', 'linux_head'),
(41, 2, 'How can I display the end of a file in Linux?|What command is used to show the last lines of a file in Linux?|Display the command to view the bottom lines of a file in Linux.|How do I use the tail command in Linux?|What is the command to print the last few lines of a file?|tail command|tail in linux|tail --help|How can I show the last N lines of a file?', 'The `tail` command in Linux is used to display the end of a file. Here are some common usages of the `tail` command:\nTo display the last 10 lines of a file:\n`tail filename.txt`\nTo display the last N lines of a file (e.g., 5 lines):\n`tail -n 5 filename.txt`\nTo continuously monitor the end of a file for new lines:\n`tail -f filename.txt`\nTo display the last part of multiple files:\n`tail file1.txt file2.txt`\nFor more options, you can use `tail --help` to display help information.', 'linux_tail'),
(42, 2, 'How can I compare files in Linux?|What command is used to find differences between files in Linux?|Display the command to compare two files in Linux.|How do I use the diff command in Linux?|What is the command to show file differences?|diff command|diff in linux|diff --help|How can I compare directories in Linux?', 'The `diff` command in Linux is used to compare files line by line. Here are some common usages of the `diff` command:\nTo compare two files and display differences:\n`diff file1.txt file2.txt`\nTo suppress normal output and display only if files differ:\n`diff -q file1.txt file2.txt`\nTo recursively compare directories and their contents:\n`diff -r directory1 directory2`\nTo create a patch file with differences between files:\n`diff -u file1.txt file2.txt > patchfile.patch`\nFor more options, you can use `diff --help` to display help information.', 'linux_diff'),
(43, 2, 'How can I compare two files byte by byte in Linux?|What command is used to find differences between binary files in Linux?|Display the command to compare two files byte by byte in Linux.|How do I use the cmp command in Linux?|What is the command to check if two files are identical?|cmp command|cmp in linux|cmp --help|How can I compare binary files in Linux?', 'The `cmp` command in Linux is used to compare two files byte by byte. Here are some common usages of the `cmp` command:\nTo compare two files and display differences:\n`cmp file1.txt file2.txt`\nTo suppress normal output and only display differences:\n`cmp -s file1.txt file2.txt`\nTo specify a limit to the number of bytes to be compared:\n`cmp -n 100 file1.txt file2.txt`\nTo show the byte and line number of the first difference:\n`cmp -l file1.txt file2.txt`\nFor more options, you can use `cmp --help` to display help information.', 'linux_cmp'),
(45, 2, 'How can I sort lines of text in Linux?|What command is used to sort lines of text alphabetically in Linux?|Display the command to sort lines of text in Linux.|How do I use the sort command in Linux?|What is the command to alphabetically sort lines?|sort command|sort in linux|sort --help|How can I sort lines of text in reverse order?', 'The `sort` command in Linux is used to alphabetically sort lines of text. Here are some common usages of the `sort` command:\nTo sort lines of text alphabetically:\n`sort filename.txt`\nTo sort lines of text in reverse order:\n`sort -r filename.txt`\nTo sort lines of text numerically:\n`sort -n filename.txt`\nTo sort lines of text and remove duplicate lines:\n`sort -u filename.txt`\nFor more options, you can use `sort --help` to display help information.', 'linux_sort'),
(46, 2, 'How can I compare two sorted files line by line in Linux?|What command is used to find common or unique lines between sorted files in Linux?|Display the command to compare sorted files line by line in Linux.|How do I use the comm command in Linux?|What is the command to compare sorted files?|comm command|comm in linux|comm --help|How can I find common lines between two sorted files in Linux?', 'The `comm` command in Linux is used to compare two sorted files line by line. Here are some common usages of the `comm` command:\nTo compare two sorted files and display lines unique to the first file:\n`comm -23 file1.txt file2.txt`\nTo display lines common to both files:\n`comm -12 file1.txt file2.txt`\nTo display lines unique to the second file:\n`comm -13 file1.txt file2.txt`\nTo specify custom delimiters and ignore case:\n`comm -i -t \'|\' file1.txt file2.txt`\nFor more options, you can use `comm --help` to display help information.', 'linux_comm'),
(47, 2, 'How can I set environment variables in Linux?|What command is used to define environment variables in Linux?|Display the command to set environment variables in Linux.|How do I use the export command in Linux?|What is the command to export environment variables?|export command|export in linux|export --help|How can I make environment variables available to child processes?', 'The `export` command in Linux is used to set environment variables. Here are some common usages of the `export` command:\nTo define an environment variable:\n`export VARIABLE_NAME=value`\nTo make an environment variable available to child processes:\n`export VARIABLE_NAME`\nTo display all environment variables:\n`export`\nTo unset an environment variable:\n`unset VARIABLE_NAME`\nFor more options, you can use `export --help` to display help information.', 'linux_export'),
(48, 2, 'How can I compress files and directories in Linux?|What command is used to create ZIP archives in Linux?|Display the command to create ZIP files in Linux.|How do I use the zip command in Linux?|What is the command to compress files and directories?|zip command|zip in linux|zip --help|How can I create password-protected ZIP files?', 'The `zip` command in Linux is used to create ZIP archives containing files and directories. Here are some common usages of the `zip` command:\nTo create a ZIP archive from a single file:\n`zip archive.zip file1.txt`\nTo create a ZIP archive from multiple files and directories:\n`zip -r archive.zip file1.txt directory1`\nTo create a password-protected ZIP archive:\n`zip -r -P password archive.zip file1.txt directory1`\nTo extract files from a ZIP archive:\n`unzip archive.zip`\nFor more options, you can use `zip --help` to display help information.', 'linux_zip'),
(49, 2, 'How can I extract files from ZIP archives in Linux?|What command is used to unzip files in Linux?|Display the command to extract files from ZIP archives in Linux.|How do I use the unzip command in Linux?|What is the command to decompress ZIP archives?|unzip command|unzip in linux|unzip --help|How can I unzip a password-protected ZIP file?', 'The `unzip` command in Linux is used to extract files from ZIP archives. Here are some common usages of the `unzip` command:\nTo extract files from a ZIP archive:\n`unzip archive.zip`\nTo extract files from a specific directory in a ZIP archive:\n`unzip archive.zip -d /path/to/destination`\nTo list the contents of a ZIP archive without extracting:\n`unzip -l archive.zip`\nTo extract files from a password-protected ZIP archive:\n`unzip -P password archive.zip`\nFor more options, you can use `unzip --help` to display help information.', 'linux_unzip'),
(50, 2, 'How can I connect to remote servers securely in Linux?|What command is used to establish SSH connections in Linux?|Display the command to connect to remote servers using SSH in Linux.|How do I use the ssh command in Linux?|What is the command to login to remote servers?|ssh command|ssh in linux|ssh --help|How can I specify a custom port for SSH connections?', 'The `ssh` command in Linux is used to connect to remote servers securely using the SSH protocol. Here are some common usages of the `ssh` command:\nTo establish an SSH connection to a remote server:\n`ssh username@hostname`\nTo specify a custom port for the SSH connection:\n`ssh -p port_number username@hostname`\nTo execute a command on the remote server without logging in:\n`ssh username@hostname \'command\'`\nTo copy files securely between hosts using SCP:\n`scp /path/to/local/file username@hostname:/path/to/remote/location`\nFor more options, you can use `ssh --help` to display help information.', 'linux_ssh'),
(51, 2, 'How can I manage system services in Linux?|What command is used to control services in Linux?|Display the command to manage system services in Linux.|How do I use the service command in Linux?|What is the command to start, stop, or restart services?|service command|service in linux|service --help|How can I check the status of a service?', 'The `service` command in Linux is used to manage system services. Here are some common usages of the `service` command:\nTo start a service:\n`service servicename start`\nTo stop a service:\n`service servicename stop`\nTo restart a service:\n`service servicename restart`\nTo check the status of a service:\n`service servicename status`\nTo enable a service to start automatically at boot time:\n`service servicename enable`\nFor more options, you can use `service --help` to display help information.', 'linux_service'),
(52, 2, 'How can I terminate processes by name in Linux?|What command is used to kill processes by name in Linux?|Display the command to terminate processes by name in Linux.|How do I use the killall command in Linux?|What is the command to end processes by name?|killall command|killall in linux|killall --help|How can I specify signal options with killall?', 'The `killall` command in Linux is used to terminate processes by name. Here are some common usages of the `killall` command:\nTo terminate all processes with a specific name:\n`killall process_name`\nTo specify a signal to send to the processes (default signal is SIGTERM):\n`killall -SIGKILL process_name`\nTo send a signal to a specific user\'s processes:\n`killall -u username process_name`\nTo kill processes owned by a specific user and in a specific process group:\n`killall -u username -g process_group process_name`\nFor more options, you can use `killall --help` to display help information.', 'linux_killall'),
(53, 2, 'How can I check disk space usage in Linux?|What command is used to display disk space usage in Linux?|Display the command to check disk space in Linux.|How do I use the df command in Linux?|What is the command to show disk space statistics?|df command|df in linux|df --help|How can I display disk space usage in human-readable format?', 'The `df` command in Linux is used to display disk space usage on file systems. Here are some common usages of the `df` command:\nTo display disk space usage for all mounted file systems:\n`df`\nTo display disk space usage in human-readable format:\n`df -h`\nTo display disk space usage for a specific file system:\n`df /dev/sda1`\nTo display disk space usage in 1K blocks:\n`df -k`\nFor more options, you can use `df --help` to display help information.', 'linux_df'),
(54, 2, 'How can I mount filesystems in Linux?|What command is used to mount filesystems in Linux?|Display the command to mount filesystems in Linux.|How do I use the mount command in Linux?|What is the command to attach filesystems?|mount command|mount in linux|mount --help|How can I mount a device to a specific directory?', 'The `mount` command in Linux is used to mount filesystems on a computer. Here are some common usages of the `mount` command:\nTo mount a device to a directory:\n`mount /dev/sdX /mnt/directory`\nTo mount a filesystem using its UUID:\n`mount UUID=xxxx-xxxx-xxxx-xxxx /mnt/directory`\nTo mount a filesystem with specific options:\n`mount -o options /dev/sdX /mnt/directory`\nTo mount all filesystems listed in `/etc/fstab`:\n`mount -a`\nFor more options, you can use `mount --help` to display help information.', 'linux_mount'),
(55, 2, 'How can I trace the route taken by packets in Linux?|What command is used to trace the route to a destination in Linux?|Display the command to perform a traceroute in Linux.|How do I use the traceroute command in Linux?|What is the command to trace the network path to a destination?|traceroute command|traceroute in linux|traceroute --help|How can I specify the maximum number of hops in a traceroute?', 'The `traceroute` command in Linux is used to trace the route taken by packets to a destination. Here are some common usages of the `traceroute` command:\nTo perform a traceroute to a destination:\n`traceroute destination`\nTo specify the maximum number of hops:\n`traceroute -m max_hops destination`\nTo specify the initial time-to-live (TTL) value:\n`traceroute -f initial_ttl destination`\nTo use ICMP Echo Request packets instead of UDP:\n`traceroute -I destination`\nFor more options, you can use `traceroute --help` to display help information.', 'linux_traceroute'),
(56, 2, 'How can I download files from the internet in Linux?|What command is used to download files in Linux?|Display the command to download files using wget in Linux.|How do I use the wget command in Linux?|What is the command to retrieve files from URLs?|wget command|wget in linux|wget --help|How can I specify the destination directory for downloaded files?', 'The `wget` command in Linux is used to retrieve files from the internet. Here are some common usages of the `wget` command:\nTo download a file from a URL:\n`wget URL`\nTo specify the destination directory for downloaded files:\n`wget -P /path/to/directory URL`\nTo continue an interrupted download:\n`wget -c URL`\nTo download multiple files from a list of URLs:\n`wget -i list.txt`\nFor more options, you can use `wget --help` to display help information.', 'linux_wget'),
(57, 2, 'How can I manage the Uncomplicated Firewall (UFW) in Linux?|What command is used to control the firewall settings in Linux?|Display the command to manage firewall rules using UFW in Linux.|How do I use the ufw command in Linux?|What is the command to configure firewall rules?|ufw command|ufw in linux|ufw --help|How can I allow or deny specific ports using UFW?', 'The `ufw` command in Linux is used to manage the Uncomplicated Firewall (UFW) settings. Here are some common usages of the `ufw` command:\nTo enable the firewall:\n`sudo ufw enable`\nTo allow traffic on a specific port:\n`sudo ufw allow port_number`\nTo deny traffic on a specific port:\n`sudo ufw deny port_number`\nTo delete a rule from the firewall:\n`sudo ufw delete allow|deny port_number`\nTo display the status of the firewall:\n`sudo ufw status`\nFor more options, you can use `ufw --help` to display help information.', 'linux_ufw'),
(58, 2, 'How can I manage firewall rules in Linux?|What command is used to configure the netfilter firewall in Linux?|Display the command to manage firewall rules using iptables in Linux.|How do I use the iptables command in Linux?|What is the command to manipulate packet filter rules?|iptables command|iptables in linux|iptables --help|How can I allow or block specific IP addresses using iptables?', 'The `iptables` command in Linux is used to configure the netfilter firewall. Here are some common usages of the `iptables` command:\nTo display current firewall rules:\n`sudo iptables -L`\nTo allow traffic on a specific port:\n`sudo iptables -A INPUT -p tcp --dport port_number -j ACCEPT`\nTo block traffic from a specific IP address:\n`sudo iptables -A INPUT -s ip_address -j DROP`\nTo save firewall rules so they persist after reboot:\n`sudo iptables-save > /etc/iptables/rules.v4`\nFor more options, you can use `iptables --help` to display help information.', 'linux_iptables'),
(59, 2, 'How can I execute commands with elevated privileges in Linux?|What command is used to run commands as another user in Linux?|Display the command to execute commands with elevated privileges using sudo in Linux.|How do I use the sudo command in Linux?|What is the command to perform administrative tasks?|sudo command|sudo in linux|sudo --help|How can I configure sudoers file to allow specific users or groups?', 'The `sudo` command in Linux is used to execute commands with elevated privileges. Here are some common usages of the `sudo` command:\nTo execute a command with elevated privileges:\n`sudo command`\nTo run a command as another user:\n`sudo -u username command`\nTo edit the sudoers file (with elevated privileges):\n`sudo visudo`\nTo add a user to the sudo group:\n`sudo usermod -aG sudo username`\nFor more options, you can use `sudo --help` to display help information.', 'linux_sudo'),
(60, 2, 'How can I display a calendar in Linux?|What command is used to show a calendar in Linux?|Display the command to view a calendar in Linux.|How do I use the cal command in Linux?|What is the command to print a calendar?|cal command|cal in linux|cal --help|How can I display a specific month or year with cal?', 'The `cal` command in Linux is used to display a calendar. Here are some common usages of the `cal` command:\nTo display the current month\'s calendar:\n`cal`\nTo display a specific month and year:\n`cal month year`\nTo display a specific year:\n`cal year`\nTo display a calendar for a specific month and year with Monday as the first day of the week:\n`cal -m month year`\nFor more options, you can use `cal --help` to display help information.', 'linux_cal'),
(61, 2, 'How can I create shortcuts for commands in Linux?|What command is used to define command aliases in Linux?|Display the command to create command shortcuts using alias in Linux.|How do I use the alias command in Linux?|What is the command to define command shortcuts?|alias command|alias in linux|alias --help|How can I list all defined aliases?', 'The `alias` command in Linux is used to create shortcuts for commands. Here are some common usages of the `alias` command:\nTo create a command alias:\n`alias shortcut=\'command\'`\nTo remove an alias:\n`unalias shortcut`\nTo display a list of defined aliases:\n`alias`\nTo make aliases permanent, add them to your shell configuration file (e.g., `.bashrc`, `.zshrc`):\n`echo \"alias shortcut=\'command\'\" >> ~/.bashrc`\nFor more options, you can use `alias --help` to display help information.', 'linux_alias'),
(62, 2, 'How can I copy and convert files in Linux?|What command is used to convert and copy files in Linux?|Display the command to perform data copying and conversion using dd in Linux.|How do I use the dd command in Linux?|What is the command to duplicate data?|dd command|dd in linux|dd --help|How can I specify block size and count in dd?', 'The `dd` command in Linux is used for copying and converting files. Here are some common usages of the `dd` command:\nTo copy data from one location to another:\n`dd if=input_file of=output_file`\nTo specify block size and count:\n`dd if=input_file of=output_file bs=block_size count=num_blocks`\nTo create a disk image:\n`dd if=/dev/sdX of=image_file`\nTo convert uppercase to lowercase:\n`dd if=input_file of=output_file conv=lcase`\nFor more options, you can use `dd --help` to display help information.', 'linux_dd'),
(63, 2, 'How can I locate binary, source, and manual page files in Linux?|What command is used to find the binary, source, and manual page locations in Linux?|Display the command to search for files using whereis in Linux.|How do I use the whereis command in Linux?|What is the command to locate binary, source, and manual page files?|whereis command|whereis in linux|whereis --help|How can I search for files in a specific directory using whereis?', 'The `whereis` command in Linux is used to locate binary, source, and manual page files. Here are some common usages of the `whereis` command:\nTo find the location of a binary executable:\n`whereis command_name`\nTo search for binary, source, and manual page files in a specific directory:\n`whereis -B -M -S /path/to/directory command_name`\nTo display help information:\n`whereis --help`\nFor more options, you can use `whereis --help` to display help information.', 'linux_whereis'),
(64, 2, 'How can I display one-line manual page descriptions in Linux?|What command is used to show short descriptions of commands in Linux?|Display the command to view manual page descriptions using whatis in Linux.|How do I use the whatis command in Linux?|What is the command to display short manual page descriptions?|whatis command|whatis in linux|whatis --help|How can I search for manual page descriptions using wildcards?', 'The `whatis` command in Linux is used to display one-line manual page descriptions. Here are some common usages of the `whatis` command:\nTo show a short description of a command:\n`whatis command_name`\nTo search for manual page descriptions using wildcards:\n`whatis \'keyword*\'`\nFor more options, you can use `whatis --help` to display help information.', 'linux_whatis'),
(65, 2, 'How can I add new users in Linux?|What command is used to create user accounts in Linux?|Display the command to add users using useradd in Linux.|How do I use the useradd command in Linux?|What is the command to create new user accounts?|useradd command|useradd in linux|useradd --help|How can I specify additional options like home directory and login shell with useradd?', 'The `useradd` command in Linux is used to add new user accounts. Here are some common usages of the `useradd` command:\nTo create a new user account:\n`sudo useradd username`\nTo specify additional options like home directory and login shell:\n`sudo useradd -m -s /bin/bash username`\nTo set the expiration date for the user account:\n`sudo useradd -e yyyy-mm-dd username`\nTo display help information:\n`useradd --help`\nFor more options, you can use `useradd --help` to display help information.', 'linux_useradd'),
(66, 2, 'How can I change passwords in Linux?|What command is used to update user passwords in Linux?|Display the command to change passwords using passwd in Linux.|How do I use the passwd command in Linux?|What is the command to modify user passwords?|passwd command|passwd in linux|passwd --help|How can I change the password for a specific user with passwd?', 'The `passwd` command in Linux is used to change user passwords. Here are some common usages of the `passwd` command:\nTo change your own password:\n`passwd`\nTo change another user\'s password (requires sudo privileges):\n`sudo passwd username`\nTo force a user to change their password on next login:\n`sudo passwd -e username`\nTo display help information:\n`passwd --help`\nFor more options, you can use `passwd --help` to display help information.', 'linux_passwd'),
(67, 2, 'How can I manage packages in Debian-based Linux distributions?|What command is used to manage packages in Debian-based Linux distributions?|Display the command to install, remove, or update packages using apt in Linux.|How do I use the apt command in Linux?|What is the command to manage software packages?|apt command|apt in linux|apt --help|How can I search for available packages with apt?', 'The `apt` command in Linux is used to manage packages in Debian-based Linux distributions such as Ubuntu. Here are some common usages of the `apt` command:\nTo install a package:\n`sudo apt install package_name`\nTo remove a package:\n`sudo apt remove package_name`\nTo update package lists:\n`sudo apt update`\nTo upgrade installed packages:\n`sudo apt upgrade`\nTo search for available packages:\n`apt search package_name`\nFor more options, you can use `apt --help` to display help information.', 'linux_apt'),
(68, 2, 'How can I manage packages in Arch Linux?|What command is used to manage packages in Arch Linux?|Display the command to install, remove, or update packages using pacman in Linux.|How do I use the pacman command in Linux?|What is the command to manage software packages?|pacman command|pacman in linux|pacman --help|How can I list installed packages with pacman?', 'The `pacman` command in Linux is used to manage packages in Arch Linux. Here are some common usages of the `pacman` command:\nTo install a package:\n`sudo pacman -S package_name`\nTo remove a package:\n`sudo pacman -R package_name`\nTo update package lists:\n`sudo pacman -Sy`\nTo upgrade installed packages:\n`sudo pacman -Syu`\nTo list installed packages:\n`pacman -Q`\nFor more options, you can use `pacman --help` to display help information.', 'linux_pacman'),
(69, 2, 'How can I manage packages in Red Hat-based Linux distributions?|What command is used to manage packages in Red Hat-based Linux distributions?|Display the command to install, remove, or update packages using yum in Linux.|How do I use the yum command in Linux?|What is the command to manage software packages?|yum command|yum in linux|yum --help|How can I list installed packages with yum?', 'The `yum` command in Linux is used to manage packages in Red Hat-based Linux distributions such as CentOS and Fedora. Here are some common usages of the `yum` command:\nTo install a package:\n`sudo yum install package_name`\nTo remove a package:\n`sudo yum remove package_name`\nTo update package lists:\n`sudo yum update`\nTo upgrade installed packages:\n`sudo yum upgrade`\nTo list installed packages:\n`yum list installed`\nFor more options, you can use `yum --help` to display help information.', 'linux_yum'),
(70, 2, 'How can I manage individual software packages in Red Hat-based Linux distributions?|What command is used to manage individual software packages in Red Hat-based Linux distributions?|Display the command to install, remove, or query individual software packages using rpm in Linux.|How do I use the rpm command in Linux?|What is the command to manage individual software packages?|rpm command|rpm in linux|rpm --help|How can I query installed packages with rpm?', 'The `rpm` command in Linux is used to manage individual software packages in Red Hat-based Linux distributions such as CentOS and Fedora. Here are some common usages of the `rpm` command:\nTo install a package:\n`sudo rpm -ivh package.rpm`\nTo remove a package:\n`sudo rpm -e package_name`\nTo query package information:\n`rpm -q package_name`\nTo display detailed information about a package:\n`rpm -qi package_name`\nFor more options, you can use `rpm --help` to display help information.', 'linux_rpm');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `dataset`
--
ALTER TABLE `dataset`
  ADD CONSTRAINT `dataset_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`category_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
